version: '3.3'

services:
  db:
    image: mysql:5.6
    container_name: mysql
    hostname: test.mysql.star.jp
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4
    volumes:
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
    - 3306:3306
